baseURL = ''
languageCode = 'en-us'
title = 'Anthony Lynch'
theme = 'gokarna'
defaultContentLanguage = 'en'
enableEmoji = true
enableRobotsTXT = true

# Choose on of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = ''
  description = "Animation | Rigging"
  avatarURL = "/images/profile_pic_001.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-l"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [    
    {name = "email", url = "mailto:rigger@anthonylynch.xyz"},
    {name = "twitter", url = "https://twitter.com/Shinobi3D"},
    {name = "vimeo", url = "https://vimeo.com/anthonylynch"},
    {name = "linkedin", url = "https://www.linkedin.com/in/anthony-lynch-6b54804/"},    
    # {name = "imdb", url = "https://www.imdb.com/name/nm4871751/?ref_=fn_al_nm_10"},
    # {name = "artstation", url = "https://www.artstation.com"},
    # {name = "twitch", url = "https://example.com"},
  ]
  metaKeywords = [ "blog", "technicalartist", "rigging", "animation" ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Reel"
    pre = "<span data-feather='film'></span>"
    url = "/reel/"
    weight = 2

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='info'></span>"
    url = "/about/"
    weight = 3    

  [[menu.main]]
    name = "Tools"
    pre = "<span data-feather='tool'></span>"
    url = "/tools/"
    weight = 4
 
  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 5  

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='clipboard'></span>"
    url = "/posts/"
    weight = 6     

  # [[menu.main]]
  #   name = "Tags"
  #   pre = "<span data-feather='tag'></span>"
  #   url = "/tags/"
  #   weight = 6

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/shinobi3D"
    weight = 7

  # [[menu.main]]
  #  identifier = "Donate"
  #  pre = "<span data-feather='dollar-sign'></span>"
  #  url = "donate"
  #  weight = 8 

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml/"
    weight = 8

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
